---
title: "Data"
format: html
execute:
  warning: false
---

{{< include _setup.qmd >}}

## **Wat zijn data?**

In de criminologie zijn we geïnteresseerd in diverse vragen die we kunnen beantwoorden aan de hand van statistisch onderzoek. Denk aan de volgende vragen:

- Hoeveel inbraken vinden er jaarlijks plaats in Kralingen?
- Wat is het gemiddelde geldbedrag waarvoor Nederlandse banken hebben geschikt in witwaszaken in 2025?
- Hoeveel misdaadjournalisten zijn er vermoord het afgelopen decennium?
- Wat is de associatie tussen drugsverslaving en delinquentie?
- In hoeverre leidt seksuele straatintimidatie tot het vermijden van bepaalde plekken?

Om deze vragen te kunnen beantwoorden, werken we met **datasets**. Een set is in de wiskunde een verzameling van dingen. Een dataset is dus een verzameling van data. Het woord **data** is afkomstig uit het Latijnse 'datum' wat letterlijk 'gegeven' betekent. Een dataset is dus een verzameling gegevens. Dit kan gaan over gegevens van mensen (bijvoorbeeld hun lengte of geslacht), maar bijvoorbeeld ook over andere dingen zoals organisaties, steden of landen. Hetgene waar de data informatie over verschaffen (mensen, organisaties, steden, landen) noemen we de **analyse-eenheid**.

In deze cursus werken we steeds met dezelfde dataset. Dit is gebaseerd op een onderzoek onder uitgaande jongeren, [Het Grote Uitgaansonderzoek](https://www.trimbos.nl/kennisbank/rapport-het-grote-uitgaansonderzoek-2023/) van het [Trimbos Instituut](https://www.trimbos.nl/). In dit onderzoek wordt onder andere gekeken hoe vaak jongeren uitgaan, wat voor soort feesten en gelegenheden ze bezoeken, wat voor middelen ze gebruiken (bijvoorbeeld alcohol of andere drugs) en hoe ze denken over drugsgebruik. Om de data te verzamelen is een online enquête afgenomen via een gerichte wervingscampagne.

Laten we eerst kijken hoe zo'n dataset eruitziet. Dat doen we met behulp van R. Zoals aangegeven in de introductie van dit online boek, het is niet erg als je nog niet snapt hoe dit werkt. Daarvoor volg je uiteraard deze cursus :)

```{r}
# laden van de voorbeeld data
voorbeeld_data <- read_rds("data/voorbeeld_data.rds")

# data inspecteren
head(voorbeeld_data) # head() voor bekijken bovenste rijen
```

Hierboven staat een 'sneak preview' van de dataset. Waar kijken we nu eigenlijk naar? De dataset verschaft informatie die we verzameld hebben over jongeren die hebben meegedaan aan de enquête. Elke rij representeert een respondent: een jongere die de enquête heeft ingevuld. De rijen zijn onze **observaties**.

Elke kolom bevat de waarde van die respondent met betrekking tot een kenmerk, de waarde die hoort bij een antwoord dat een respondent gaf op een in de enquête gestelde vraag. De waarden van respondenten op kenmerken kunnen variëren van respondent tot respondent. Niet iedereen is even oud, gebruikt even vaak drugs, heeft dezelfde opleiding etc. De variatie in een bepaald kenmerk meten we met behulp van **variabelen**. Deze zien we terug in de kolommen. De kern van statistiek is dat we alle variatie in kenmerken gaan gebruiken om onderzoeksvragen zoals die hierboven te kunnen beantwoorden.

We kunnen bijvoorbeeld zien dat de eerste respondent een vrouw is, 30 jaar oud, en een middelbaar opleidingsniveau heeft.

De vierde en vijfde kolom geven aan of iemand ooit alcohol heeft gedronken of in het afgelopen jaar. De voorbeeld data toont dat vijf respondenten het afgelopen jaar alcohol hebben gedronken en één respondent niet.

### Missende waarden

Wat je misschien ook is opgevallen, is dat in de vijfde rij bij opleidingsniveau 'NA' staat. Dit staat voor Not Available en geeft aan dat er geen valide waarde is voor deze respondent op dit kenmerk. Van deze persoon weten we het opleidingsniveau dus niet. Dit noemen we een **missende waarde**.

Missende waarden komen vaak voor in onderzoek om diverse redenen. Zo kunnen mensen een vraag verkeerd invullen, een vraag per ongeluk overslaan, of een vraag niet willen beantwoorden. Dit laatste zien we vaker bij gevoelige vragen, bijvoorbeeld over gedrag dat maatschappelijk wordt afgekeurd (drugsgebruik!).

Missende waarden hoeven niet altijd een probleem te zijn. Dit hangt af van de de aard van missende waarden en de hoeveelheid. In de practica besteden we hier meer aandacht aan.
