# Setup

Voor we aan de slag kunnen met kwantitatief onderzoek in R, moeten we alle benodigde software en libraries installeren. Rstudio is het programma waarin we de analyses draaien en resultaten opvragne. Github is zogenaamde versiebeheer software waar dit handboek open-source gehost is. Het voordeel daaarvan is dat het boek open toegangelijk is, makkelijk te updaten en voor jullie makkelijk om mee te werken tijdens de lessen.

Om het werken met dit boek te vergemakkelijken, kun je het boek in jouw R inladen zodat je de code en bijbehorende data makkelijk kunt gebruiken voor de opdrachten tijdens de werkgroepen.

**Software:**

-   [Rstudio en R](https://posit.co/download/rstudio-desktop/)

-   [Github Desktop](https://desktop.github.com/download/)

**Stappenplan:**

1.  Download en installeer
2.  Maak een account aan op Github
3.  

Na installatie van de benodigde software moeten we R gereed maken door de juiste packages te installeren. Dat doe je door RStudio te openen en in je console het volgende te typen:

```{r}
# install.packages("ggplot2")
```
